name: Build and Package WingGifEditor2

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
        default: 'windows-latest'
      qt_version:
        description: 'Qt Version'
        required: true
        type: choice
        options:
          - 5.15.2
          - 6.6.2
        default: '6.6.2'
      arch:
        description: 'Architecture'
        required: true
        type: choice
        options:
          - win64_msvc2019_64
          - gcc_64
        default: 'win64_msvc2019_64'

permissions:
  contents: write
  
env:
  BUILD_TYPE: Release

jobs:
  build-and-package:
    runs-on: ${{ inputs.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      with:
        submodules: recursive
        fetch-depth: 0
        fetch-tags: true
        
    - name: Validate inputs
      run: |
        if [[ "${{ inputs.os }}" == "windows-latest" && "${{ inputs.arch }}" == "gcc_64" ]]; then
          echo "Invalid combination: windows-latest cannot use gcc_64"
          exit 1
        fi
        if [[ "${{ inputs.os }}" == "ubuntu-latest" && "${{ inputs.arch }}" == "win64_msvc2019_64" ]]; then
          echo "Invalid combination: ubuntu-latest cannot use win64_msvc2019_64"
          exit 1
        fi
      shell: bash
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ inputs.qt_version }}
        host: ${{ inputs.os == 'windows-latest' && 'windows' || 'linux' }}
        target: 'desktop'
        arch: ${{ inputs.arch }}
        cache: true
        tools: 'tools_cmake'

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Display install directory structure
      run: |
        echo "=== Install directory structure ==="
        if [ "${{ runner.os }}" == "Windows" ]; then
          # Windows系统使用dir命令
          dir install /s
        else
          # Linux/macOS使用find命令
          find install -type f | head -20
        fi
        echo "=================================="
      shell: bash

    - name: Package Windows (Windows)
      if: inputs.os == 'windows-latest'
      run: |
        echo "=== Starting Windows packaging ==="
        
        # Create deployment directory
        mkdir package
        
        # Display install contents before copying
        echo "=== Install directory contents ==="
        dir install /s
        
        # Copy executable and dependencies
        xcopy /E /I install\* package\
        
        echo "=== Package directory after copy ==="
        dir package /s
        
        # Use windeployqt to collect all Qt dependencies
        windeployqt --release --no-translations --no-system-d3d-compiler --no-opengl-sw package\WingGifEditor2.exe
        
        echo "=== Package directory after windeployqt ==="
        dir package /s
        
        # Create zip archive
        cd package
        7z a -tzip ..\WingGifEditor2-windows-${{ inputs.qt_version }}-${{ inputs.arch }}.zip .
        
        echo "=== Final package created ==="
        dir ..\*.zip
      shell: cmd

    - name: Package Linux (Linux)
      if: inputs.os == 'ubuntu-latest'
      run: |
        echo "=== Starting Linux packaging ==="
        
        # Display install contents before copying
        echo "=== Install directory contents ==="
        find install -type f -exec ls -la {} \;
        
        # Create AppImage structure
        mkdir -p package/AppDir/usr/bin
        mkdir -p package/AppDir/usr/lib
        mkdir -p package/AppDir/usr/share/applications
        mkdir -p package/AppDir/usr/share/icons/hicolor/256x256/apps
        
        # Copy executable and libraries
        cp -r install/* package/AppDir/usr/bin/
        
        echo "=== AppDir structure after copy ==="
        find package/AppDir -type f -exec ls -la {} \;
        
        # Create desktop file
        cat > package/AppDir/usr/share/applications/wing-gif-editor.desktop << EOF
        [Desktop Entry]
        Type=Application
        Name=WingGifEditor2
        Exec=WingGifEditor2
        Icon=WingGifEditor2
        Categories=Graphics;2DGraphics;RasterGraphics;
        EOF
        
        # Copy icon
        cp images/icon.png package/AppDir/usr/share/icons/hicolor/256x256/apps/WingGifEditor2.png
        
        # Download and use linuxdeployqt
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        
        # Create AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage package/AppDir/usr/share/applications/wing-gif-editor.desktop -appimage
        
        echo "=== AppImage created ==="
        ls -la *.AppImage
        
        # Rename output
        mv WingGifEditor2*.AppImage WingGifEditor2-linux-${{ inputs.qt_version }}-${{ inputs.arch }}.AppImage
        
        echo "=== Final package ==="
        ls -la *.AppImage
      shell: bash

    - name: Upload executable package (Windows)
      if: inputs.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: WingGifEditor2-windows-${{ inputs.qt_version }}-${{ inputs.arch }}
        path: WingGifEditor2-windows-${{ inputs.qt_version }}-${{ inputs.arch }}.zip
        retention-days: 30

    - name: Upload executable package (Linux)
      if: inputs.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: WingGifEditor2-linux-${{ inputs.qt_version }}-${{ inputs.arch }}
        path: WingGifEditor2-linux-${{ inputs.qt_version }}-${{ inputs.arch }}.AppImage
        retention-days: 30

    - name: Upload build cache
      uses: actions/upload-artifact@v4
      with:
        name: WingGifEditor2-${{ inputs.os == 'windows-latest' && 'windows' || 'linux' }}-${{ inputs.qt_version }}-${{ inputs.arch }}-build-cache
        path: build
        retention-days: 7

    - name: Display final build artifacts
      run: |
        echo "=== Build completed successfully! ==="
        echo "=== All generated files ==="
        if [ "${{ inputs.os }}" == "windows-latest" ]; then
          dir *.zip /s
          dir *.exe /s 2>/dev/null || echo "No exe files found"
        else
          ls -la *.AppImage 2>/dev/null || echo "No AppImage files found"
          find . -name "*.deb" -o -name "*.rpm" -o -name "*.tar.gz" | head -20
        fi
        echo "======================================"
      shell: bash
    
